// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncwenrmrgdyctoqluamj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jd2Vucm1yZ2R5Y3RvcWx1YW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDk3MzEsImV4cCI6MjA2MTgyNTczMX0.hQcY9jpEHzcsGZ1qEpJgNVYGkiXd2d3GaGT9p3zrxkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);